# Generated by Django 5.0.7 on 2024-07-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTrafficVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(help_text='Stores row data as a JSON string.')),
            ],
        ),
        migrations.DeleteModel(
            name='TrafficVolume',
        ),
    ]
