# Generated by Django 5.0.7 on 2024-07-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdata', '0002_dynamictrafficvolume_delete_trafficvolume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamictrafficvolume',
            name='data',
            field=models.JSONField(help_text='Stores row data as JSON.'),
        ),
    ]
